### ISSUE TITLE
How to use it for nested CSS

### ISSUE THREAD

**Issue by kockhwie** [coliff/dark-mode-switch#10]
How to use it for nested CSS elements like:

```css
        .nav-tabs .nav-link {             
            border: 1px solid #fff;
            background-color: #f1f6fb;
        }

        .nav-tabs .nav-link.active{
            border: 1px solid #fff;
            background-color: #fff;
        }
```
Thanks. Awesome job.
